esphome:
  name: esp32-wroom-32
  friendly_name: ESP32 WROOM 32
  name_add_mac_suffix: true

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:

api:

http_request:

ota:
  - platform: esphome
  - platform: http_request

update:
  - platform: http_request
    id: firmware_update_start
    name: Firmware Update
    source: https://diekruecke.github.io/esphome-templates/firmware/diekruecke-esp32-wroom-32/manifest.json

button:
  - platform: template
    name: Update Firmware from Github
    on_press:
      then:
        - update.perform:
            id: firmware_update_start

wifi:
  ap:

web_server:
  version: 3

captive_portal:

demo: