title: DieKruecke's ESPHome Firmware Collection
description: flash and forget
remote_theme: pages-themes/hacker@v0.2.0

show_downloads: false
# google_analytics: [Your Google Analytics tracking ID]

plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one